# Generated by Django 4.1.7 on 2023-03-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_userprofile_email_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nacimiento',
        ),
    ]
