# Generated by Django 4.1 on 2023-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=264, null=True)),
                ('latitud', models.CharField(max_length=264, null=True)),
                ('longitud', models.CharField(max_length=264, null=True)),
                ('invitados', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
